export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
